[Distribution]
Distribution=ubuntu
Release=noble
Architecture=x86-64

[Content]
Packages=
  systemd
  bash
  iproute2
  udev
  ca-certificates
  linux-image-6.8.0-111-generic
ExtraTrees=overlay

[Output]
Format=directory
Output=zeroseal
SourceDateEpoch=0
MachineId=ffffffffffffffffffffffffffffffff
RemoveFiles=
  /var/log/alternatives.log
  /var/cache/ldconfig/aux-cache

[Build]
ToolsTree=default
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=noble
ToolsTreePackages=cryptsetup-bin
